### ISSUE TITLE
How do I change embed to use https?

### ISSUE THREAD

**Issue by amirshawn** [mpratt/Embera#19]
Hi, 
I am trying to use this on a secure server, is it possible to change embed links to https?  I see a function for it, just not sure how to use it.

Thanks,
Amir

**Comment by mpratt** [comment]
Hi **amirshawn**,

Right now the library doesn't provide an easy way to force/return "https" embed codes. You either have to extend providers or write something like `echo str_replace('"http://', '"https://', $embera->autoEmbed($text));`. (which is really ugly).

Some providers allow parameters on the oembed request in order to return the embed code with a `https`. For example Youtube.

You can change the [line 21 on the Youtube provider](https://github.com/mpratt/Embera/blob/master/Lib/Embera/Providers/Youtube.php#L21) 

```php
protected $apiUrl = 'http://www.youtube.com/oembed?format=json';
```

with

```php
protected $apiUrl = 'http://www.youtube.com/oembed?format=json&scheme=https';
```

Other method, if you only use a couple of Providers could be extending them. Lets take for example DailyMotion:

```php
// Create a new class that extends the DailyMotion Provider
class CustomDailyMotion extends \Embera\Providers\DailyMotion
{
    /** inline {@inheritdoc} */
    protected function modifyResponse(array $response = array())
    {
        $response = parent::modifyResponse($response);
        if (!empty($response['html'])) {
            $response['html'] = str_replace('"http://', '"https://', $response['html']);
        }
        
        return $response;
    }
}

$embera = new Embera\Embera();
$embera->addProvider('*.dailymotion.com', 'CustomDailyMotion');
echo $embera->autoEmbed(........);
```

Or the other way could be, changing the [Service Adapter::modifyResponse](https://github.com/mpratt/Embera/blob/master/Lib/Embera/Adapters/Service.php#L186) but that change wont work on all providers and will be overwritten every time you update to newer versions.

We also have to take into account that there are a few providers that don't support https yet.

Fake responses normally return only "http" addresses.
I'm working on making the next major version of this library more friendly on that aspect.

I'm going to leave this issue open for now until the next version arrives.

**Comment by amirshawn** [comment]
Thank you for the help! I got Youtube to work and that was the main provider I was interested.  I look forward to your next version.

**Comment by robbytaylor** [comment]
I've been thinking about how this could be implemented and was wondering whether something along these lines is all that's required:

* Allow $apiUrl to be either a string or an array. If it's a string then it would be assumed to be http, making it backwards compatible. If it's an array than it would be an associative array of scheme => URL. So for the YouTube example it would be:

```php
protected $apiUrl = [
    'http' => 'http://www.youtube.com/oembed?format=json',
    'https' => 'http://www.youtube.com/oembed?format=json&scheme=https'
];
```

If a provider doesn't support HTTP then it would just be:

```php
protected $apiUrl = 'http://www.aproviderapi.com';
```

* Add a method to the Embera class to set whether to use HTTP or HTTPS (setScheme() maybe)?. If it's not called then HTTP would be the default, keeping the current behaviour.

* *somehow* `Embera:: getProviders()` would only return providers which have an API URL defined for the current scheme.

**Comment by jaswsinc** [comment]
Great stuff. I just wanted to add that I'd love to see more control over this also. With the upcoming widespread use of HTTP/2, everything is going to start moving toward `https://`. So my feeling is that all of these should default to `https://` whenever possible, and perhaps there could be a config. option that allow me to disable any provider that doesn't support `https://` yet.

https://http2.github.io/

**Comment by simonfrance** [comment]
Another way of adding https while waiting for the 2.0 milestone of Embera.

This may not work with some providers (those who don't support https, but as you cannot include non-https content to a http server, it works as badly as without the modification :)

```php
    public function autoEmbed($body = null)
    {
        if (!is_string($body)) {
            $this->errors[] = 'For auto-embedding purposes, the input must be a string';
        } elseif ($data = $this->getUrlInfo($body)) {
            $table = array();
            foreach ($data as $url => $service) {
                if (!empty($service['html'])) {
                    $table[$url] = $service['html'];
                }
            }
			if($this->isSecure()) array_walk($table, array($this, "addHttps"));
            return str_replace(array_keys($table), array_values($table), $body);
        }

        return $body;
    }

	public function addHttps(&$item, $key){
		$item = str_replace('"http://', '"https://', $item);
	}
	public function isSecure(){
		$isSecure = false;
		if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') {
    		$isSecure = true;
		} elseif (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' || !empty($_SERVER['HTTP_X_FORWARDED_SSL']) && $_SERVER['HTTP_X_FORWARDED_SSL'] == 'on') {
			$isSecure = true;
		}
		return $isSecure;
	}
```

**Comment by mpratt** [comment]
Hi!

The newest version 2.0, has the configuration option to use only providers that support https.
```php
use Embera\Embera;

$config = [
    'https_only' => true
];

$embera = new Embera($config);
// do your thing
```
