### ISSUE TITLE
Adding custom query string parameters to a service

### ISSUE THREAD

**Issue by jrean** [mpratt/Embera#24]
Hi,

```
        $config = array(
            'custom_params' => array(
                'Youtube' => array('showinfo' => 0)
            )
        );

        $embera = new Embera($config);
```

If I use 'Youtube' or 'youtube' it doesn't work, I can't add custom query params to a service.
The returned iframe doesn't contain such param.

Did I miss something?

Thank you for the great work.

J.

**Comment by mpratt** [comment]
Hi **Jrean**,

Im so sorry for the late response. The custom query params option is meant to be sent to the oembed endpoint and depending on the provider it does affect the response. However it seems as the youtube endpoint doesnt understand the parameter you want to send.

That being said, perhaps the best way to add the showinfo parameter to the resulting iframe would be to extend the `Youtube` provider and add/write a `modifyResponse` and register the new provider with the `addProvider` method.

Since this is a very old issue I'm not going to provide any code sample, however if you need some help, let me know and I'll do my best to give you a hand with that.
