### ISSUE TITLE
Bug: autoEmbed replacing embed URLs incorrectly

### ISSUE THREAD

**Issue by assembledadam** [mpratt/Embera#27]
Embera::autoEmbed() does a str_replace on the embed URLs with the replacement HTML, but this is prone to a bug.

Str_replace here replaces a embed URLs containing text that exactly matches URLs later on in the replacement text, so the URLs later on are truncated, and the net result is one or more duplicated embed objects with superfluous text.

I have created an example test case to illustrate the issue:
https://gist.github.com/assembledadam/8c25c24956cc496a9203

**Comment by mpratt** [comment]
Thank you very much *assembledadam* for your report!

You are right, that is indeed a stupid bug. I did look at your pull request and am sure that it should fix the problem.

However I'm almost certain that using the `strtr` function instead of `str_replace`, should also fix this issue. I will test both alternatives and see which one works best.

Again thank you very much for the report!
