### ISSUE TITLE
Facebook embed bug

### ISSUE THREAD

**Issue by assembledadam** [mpratt/Embera#36]
When embedding Facebook with a formatter, you get 'Array to string conversion'.

To reproduce, use the following:

````
$text = 'https://www.facebook.com/adam.j.mccann/posts/10156943904420037?pnref=story';
$embera = new \Embera\Embera();

$formatter = new \Embera\Formatter($embera);
$formatter->setTemplate('{html}');

return $formatter->transform($text);
````

This is caused by the provider file here (Embera\Providers\Facebook, line 162)
````
// Backup the real response
$response['raw']['html'] = $response['html'];
````

There may be other providers that have multi-dimensional arrays on the response that would also cause this issue.

**Comment by assembledadam** [comment]
Oh, and the Facebook Embed provider also appears to be cutting off the embed (although from the code it looks like this is based on the response height, so not sure there).

**Comment by mpratt** [comment]
Hi @assembledadam ! Thanks for the report!

You are right, It was a bug when a response contained a multidimentional array. I Fixed it and will be tagging a new release soon.

The problem you are experiencing with the facebook embed height is known. The problem is that the facebook html response contains javascript that could cause problems if you are already using facebooks javascript sdk or if you do multiple facebook embeds on the same page. So the best solution I found was to create and return an iframe, but the problem is that facebook normally doesn't return the height of the embed, so I had to add a minimum height of 650px, which in some cases isnt enough.

Every iframe has a distinct id so you can change the height via css. Every iframe has also a class that you can use to also change the height via css.

On the other hand, for the facebook provider, you can try and use the `{raw.html}` code (or `$response['raw']['html'];`)  to get the original facebook response and see if it works better for you.

**Comment by assembledadam** [comment]
Great - thanks for the quick fix & info regarding the known issue/possible workaround !
