### ISSUE TITLE
Animoto using a s3.amazonaws.com url.

### ISSUE THREAD

**Issue by Steelcrusher** [mpratt/Embera#50]
one of the videos i get from my client use the follwing url:
https://s3.amazonaws.com/embed.animoto.com/play.html?w=swf/production/vp1&e=1488492260&f=fb9mx8JbJlfzThO865PLvg&d=0&m=p&r=360p&volume=100&start_res=360p&i=m&asset_domain=s3-p.animoto.com&animoto_domain=animoto.com&options=

Not sure how to adapt to make Embera able to use it.

**Comment by mpratt** [comment]
Hi!

The library cannot detect that url as Animoto.com, because the host is amazonws.com.
and on the other hand the schema supported by animoto's oembed is : https://animoto.com/play/* and not play.html

It might be possible to construct a valid url based on the one you have there but im not sure how to do it.

There is not really other solution I can think of, so im closing this issue due to it and because its old. Sorry for the late response.
