### ISSUE TITLE
How about dropping support php version prior to 7.2?

### ISSUE THREAD

**Issue by vkhramtsov** [mpratt/Embera#64]
Hi!
Currently only php version 7.2, 7.3 and 7.4 officially supported, also you are testing only these versions. Also for tests you are using phpunit version, which require at least php version 7.2. 
What do you think about dropping support of php versions prior 7.2 in composer.json? I can create PR for this.

**Comment by mpratt** [comment]
Hi @vkhramtsov!

This is something I've been thinking for a while now, even before launching version 2.0. I am not officialy supporting older versions of PHP, thats why I'm also keeping the 1.x.x branch which supports PHP 5. I plan on giving some basic support (mostly security and minor updates) to version 1.x.x.

However I know version 2.0 runs on PHP 5.6, I have made some basic tests and everything seems to be working just fine and I don't think that is going to change unless I do another rewrite of the library and start using functionality not available on older versions.

So, to be completely honest, I'm not sure If we should "hard drop" support on composer.json yet. 

Maybe lets hear if anyone else comments on this issue, in order to see another perspective. Im leaving this issue open for a month or so and read if anyone has something to say about this before making a decision.

**Comment by vkhramtsov** [comment]
It looks like nobody wants to write something, so 1:1, no winner ;)

**Comment by mpratt** [comment]
I decided that when the time comes to tag version **2.1.0**, I'll be making the switch to php >= 7.2 on composer.json. I dont know when that is going to happen, but I think thats the best option right now.

Thanks for your input @vkhramtsov !
