### ISSUE TITLE
Instagram oEmbed is deprecated

### ISSUE THREAD

**Issue by TiGR** [mpratt/Embera#87]
So [the docs](https://developers.facebook.com/docs/instagram/oembed) specify that oEmbed would stop working starting September 7 and it is not working right now anonymously, it requires `access_token`.

**Comment by mpratt** [comment]
Hi @TiGR !

Thanks for the report! What version of Embera are you using?
Version +2.0 has the new implementation so you can do the following for instagram / facebook:

```php
$config = [
 'instagram_access_token' => 'yourtokenforinsta',
 'facebook_access_token' => 'yourtokenforfacebook'
];

$embera = new Embera($config);
```
Let me know if this works for you. 

I updated the documentation for [Facebook](https://github.com/mpratt/Embera/blob/21afee7445dc6a445ce81226f9e6aee442a6978f/doc/providers/Facebook.md) and [Instagram](https://github.com/mpratt/Embera/blob/21afee7445dc6a445ce81226f9e6aee442a6978f/doc/providers/Instagram.md) in order to make it clearer.
